In [ ]:
import pandas as pd
from pathlib import Path
import requests
from html import escape
import os
from dotenv import load_dotenv


load_dotenv(override=True)

file_path = os.getenv("EXCEL_FILE_PATH")

excel_file = pd.ExcelFile(file_path)

df = pd.read_excel(file_path, sheet_name="TPP-2020")

# Fetch a customer to alert

CUSTOMER_COLUMN = "Sold-to-party Name"  
CUSTOMER_NAME = "LIM SIEK"            

matched_customer = df[
    df[CUSTOMER_COLUMN].astype(str).str.contains(CUSTOMER_NAME, case=False, na=False)
]

display(matched_customer)

customer_row = matched_customer.iloc[0]

def format_customer_message(row):
    message = "Customer Alert\n"
    message += "====================\n\n"

    for column, value in row.items():
        if pd.notna(value):
            message += f"{column}: {value}\n"

    return message

message_text = format_customer_message(customer_row)

BOT_TOKEN = os.getenv("FATHER_BOT_TOKEN")
CHAT_ID = int(os.getenv("CHAT_ID"))

def send_text_to_telegram(bot_token, chat_id, message):
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"

    payload = {
        "chat_id": chat_id,
        "text": f"<pre>{escape(message)}</pre>",
        "parse_mode": "HTML"
    }

    response = requests.post(url, data=payload)
    print(response.json())

send_text_to_telegram(BOT_TOKEN, CHAT_ID, message_text)

['Note', 'TPP-2020']
['No', 'Material Name', 'Sold-to-party ID', 'Sold-to-party Name', 'Ship-to-party ID', 'Ship-to-party Name', 'Sales Order No', 'Delivery No', 'Billing Doc.', 'Reference', 'Billing Code', 'Billing Description', 'Billing item', 'Material No.', 'Material Group', 'Del Qty', 'Plant', 'Stor. Location', 'Sales Unit', 'Sales Employee ID', 'Sales Employee Name', 'Customer Group', 'Description', 'Billing Date', 'Selling Price', 'Selling Price (VAT)', 'Net Selling Price', 'Transport Charge', 'Tran. Charge(ZR18)', 'Transport Charge(VAT)', 'Net Transport Charge', 'Mixing Charge', 'Mixing Charge(VAT)', 'Net Mixing Charge', 'Pumping Charge', 'Pumping Charge(VAT)', 'Net Pumping Charge', 'Net Unit Price', 'Amount', 'Amount (VAT)', 'Net Amount', 'VAT Percentage(%)', 'Item Category', 'Create On', 'Create By', 'Sales District', 'Devision', 'Term of Payment', 'Quotation No.', 'I2C Ticket', 'Segmentation', 'Segmentation Des.', 'Customer Type', 'Cust. Type Des.', 'Project Group', 'Project Group Des.', 'Project Type', 'Project Type Des.', 'Company Code', 'Accounting Doc', 'Fiscal Year', 'Clearing Doc', 'Clearing Date', 'Region', 'Region Description', 'Sale Org', 'Stationary Charge', 'Stationary Charge(VAT)', 'Net Station Charge', 'Discount', 'Forwarding agent', "Forwarding agent's name", 'Route number', 'Route description', 'Address', 'Customer Group 5', 'PO Number', 'Truck Number', 'Qty Dis. (ZR14)', 'Trans/TO (ZR15)', 'Disc. on Trans (ZR20)', 'COGS', 'COGS (per)', 'COGS (per UOM)', 'Special Discount', 'Disc COD (ZR22)', 'Disc on Transport (ZR23)', 'Search Term', 'Insert_Date']

,No,Material Name,Sold-to-party ID,Sold-to-party Name,Ship-to-party ID,Ship-to-party Name,Sales Order No,Delivery No,Billing Doc.,Reference,...,Trans/TO (ZR15),Disc. on Trans (ZR20),COGS,COGS (per),COGS (per UOM),Special Discount,Disc COD (ZR22),Disc on Transport (ZR23),Search Term,Insert_Date
19,NaN,PVC Pipe 8.5 Bar 100mm - 4m - Blue,12001943,LIM SIEK,15004314,Site: Borey Bunly,67806449.0,800108498,21407808.0,21407808.0,...,0.0,0.0,12.75,1,PC,0.0,NaN,NaN,012852170,NaN
20,NaN,PVC Pipe 8.5 Bar 80mm - 4m - Blue,12001943,LIM SIEK,15004314,Site: Borey Bunly,67806449.0,800108498,21407808.0,21407808.0,...,0.0,0.0,7.86,1,PC,0.0,NaN,NaN,012852170,NaN
21,NaN,PVC Pipe 8.5 Bar 55mm - 4m - Blue,12001943,LIM SIEK,15004314,Site: Borey Bunly,67806449.0,800108498,21407808.0,21407808.0,...,0.0,0.0,3.79,1,PC,0.0,NaN,NaN,012852170,NaN
201,NaN,PVC Pipe 5 Bar 35mm - 4m - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67806578.0,800108649,21407956.0,21407956.0,...,0.0,0.0,1.08,1,PC,0.0,NaN,NaN,012852170,NaN
202,NaN,PVC Pipe 5 Bar 40mm - 4m - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67806578.0,800108649,21407956.0,21407956.0,...,0.0,0.0,1.26,1,PC,0.0,NaN,NaN,012852170,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299474,NaN,Tee 55mm 8.5 bar - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67888683.0,800315526,21707595.0,21707595.0,...,0.0,0.0,0.26,1,PC,0.0,0.0,-0.19,010882287,NaN
299475,NaN,Socket 80mm x 55mm 8.5 Bar - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67888683.0,800315526,21707595.0,21707595.0,...,0.0,0.0,0.21,1,PC,0.0,0.0,-0.30,010882287,NaN
299476,NaN,Fitting Tee 8.5 Bar 80mm - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67888683.0,800315526,21707595.0,21707595.0,...,0.0,0.0,0.44,1,PC,0.0,0.0,-0.49,010882287,NaN
299477,NaN,PVC Fitting Tee 8.5 Bar 100mm - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67888683.0,800315526,21707595.0,21707595.0,...,0.0,0.0,0.76,1,PC,0.0,0.0,-0.08,010882287,NaN
299478,NaN,Chip Mong Pipe 8.5 Bar 40mm x 4m - Blue,12001943,LIM SIEK,12001943,LIM SIEK,67888686.0,800315530,21707597.0,21707597.0,...,0.0,0.0,2.01,1,PC,0.0,0.0,-23.50,010882287,NaN

Customer Alert
====================

Material Name: PVC Pipe 8.5 Bar 100mm - 4m - Blue
Sold-to-party ID: 12001943
Sold-to-party Name: LIM SIEK
Ship-to-party ID: 15004314
Ship-to-party Name: Site: Borey Bunly
Sales Order No: 67806449.0
Delivery No: 800108498
Billing Doc.: 21407808.0
Reference: 21407808.0
Billing Code: ZRF2
Billing Description: CMI Invoice
Billing item: 10.0
Material No.: PP8B00100
Material Group: 230000
Del Qty: 30.0
Plant: TPP1
Stor. Location: TP02
Sales Unit: PC
Sales Employee ID: 90009651
Sales Employee Name: CHHUNNY SORN
Customer Group: 2.0
Description: Wholesaler
Billing Date: 2020-01-03 00:00:00
Selling Price: 23.37
Selling Price (VAT): 0.0
Net Selling Price: 23.37
Transport Charge: 0
Tran. Charge(ZR18): 0
Transport Charge(VAT): 0
Net Transport Charge: 0
Mixing Charge: 0.0
Mixing Charge(VAT): 0.0
Net Mixing Charge: 0.0
Pumping Charge: 0.0
Pumping Charge(VAT): 0.0
Net Pumping Charge: 0.0
Net Unit Price: 0.0
Amount: 525.82
Amount (VAT): 0.0
Net Amount: 525.82
VAT Percentage(%): 0
Item Category: TAN
Create On: 2020-01-03 00:00:00
Create By: 90010775
Sales District: Phnom Penh
Devision: P1
Term of Payment: ZC15
Company Code: CMCR
Accounting Doc: 2100000031.0
Fiscal Year: 2020.0
Clearing Doc: 100009950.0
Clearing Date: 2020-03-13 00:00:00
Region: 1
Region Description: Phnom Penh
Sale Org: TPP1
Stationary Charge: 0.0
Stationary Charge(VAT): 0.0
Net Station Charge: 0
Discount: -175.28
Forwarding agent: 102563.0
Forwarding agent's name: CARGO TRANSPORTATION AGENT (CTA)
Route number: ZR1005
Route description: Factory RT & TPP -> Khan Dangkor
PO Number: No.022122 DTD
Truck Number: REUMOK CTA
Qty Dis. (ZR14): 0.0
Trans/TO (ZR15): 0.0
Disc. on Trans (ZR20): 0.0
COGS: 12.75
COGS (per): 1
COGS (per UOM): PC
Special Discount: 0.0
Search Term: 012852170

{'ok': True, 'result': {'message_id': 5, 'from': {'id': 8503858271, 'is_bot': True, 'first_name': 'ToBi', 'username': 'stociybot'}, 'chat': {'id': 1311053886, 'first_name': 'LIMPHENGEANG', 'username': 'than_limphengeang', 'type': 'private'}, 'date': 1783560086, 'text': "Customer Alert\n====================\n\nMaterial Name: PVC Pipe 8.5 Bar 100mm - 4m - Blue\nSold-to-party ID: 12001943\nSold-to-party Name: LIM SIEK\nShip-to-party ID: 15004314\nShip-to-party Name: Site: Borey Bunly\nSales Order No: 67806449.0\nDelivery No: 800108498\nBilling Doc.: 21407808.0\nReference: 21407808.0\nBilling Code: ZRF2\nBilling Description: CMI Invoice\nBilling item: 10.0\nMaterial No.: PP8B00100\nMaterial Group: 230000\nDel Qty: 30.0\nPlant: TPP1\nStor. Location: TP02\nSales Unit: PC\nSales Employee ID: 90009651\nSales Employee Name: CHHUNNY SORN\nCustomer Group: 2.0\nDescription: Wholesaler\nBilling Date: 2020-01-03 00:00:00\nSelling Price: 23.37\nSelling Price (VAT): 0.0\nNet Selling Price: 23.37\nTransport Charge: 0\nTran. Charge(ZR18): 0\nTransport Charge(VAT): 0\nNet Transport Charge: 0\nMixing Charge: 0.0\nMixing Charge(VAT): 0.0\nNet Mixing Charge: 0.0\nPumping Charge: 0.0\nPumping Charge(VAT): 0.0\nNet Pumping Charge: 0.0\nNet Unit Price: 0.0\nAmount: 525.82\nAmount (VAT): 0.0\nNet Amount: 525.82\nVAT Percentage(%): 0\nItem Category: TAN\nCreate On: 2020-01-03 00:00:00\nCreate By: 90010775\nSales District: Phnom Penh\nDevision: P1\nTerm of Payment: ZC15\nCompany Code: CMCR\nAccounting Doc: 2100000031.0\nFiscal Year: 2020.0\nClearing Doc: 100009950.0\nClearing Date: 2020-03-13 00:00:00\nRegion: 1\nRegion Description: Phnom Penh\nSale Org: TPP1\nStationary Charge: 0.0\nStationary Charge(VAT): 0.0\nNet Station Charge: 0\nDiscount: -175.28\nForwarding agent: 102563.0\nForwarding agent's name: CARGO TRANSPORTATION AGENT (CTA)\nRoute number: ZR1005\nRoute description: Factory RT & TPP -> Khan Dangkor\nPO Number: No.022122 DTD\nTruck Number: REUMOK CTA\nQty Dis. (ZR14): 0.0\nTrans/TO (ZR15): 0.0\nDisc. on Trans (ZR20): 0.0\nCOGS: 12.75\nCOGS (per): 1\nCOGS (per UOM): PC\nSpecial Discount: 0.0\nSearch Term: 012852170", 'entities': [{'offset': 0, 'length': 1789, 'type': 'pre'}]}}

In [4]:
%load_ext autoreload
%autoreload 2

from Methods.config import load_settings
from Methods.excel_service import (
    load_excel_sheet,
    filter_last_one_year,
    find_customer
)
from Methods.telegram_service import (
    format_customer_message,
    send_text_to_telegram
)

settings = load_settings()

df = load_excel_sheet(
    file_path=settings["file_path"],
    sheet_name=settings["sheet_name"]
)

df_last_year, start_date, latest_date = filter_last_one_year(
    df=df,
    date_column=settings["date_column"]
)

print("Latest date:", latest_date)
print("Start date:", start_date)
print("Rows after filter:", len(df_last_year))

CUSTOMER_NAME = "LIM SIEK"

matched_customer = find_customer(
    df=df_last_year,
    customer_column=settings["customer_column"],
    customer_name=CUSTOMER_NAME
)

display(matched_customer)

if matched_customer.empty:
    print("No customer found.")
else:
    customer_row = matched_customer.iloc[0]

    message_text = format_customer_message(customer_row)

    result = send_text_to_telegram(
        bot_token=settings["bot_token"],
        chat_id=settings["chat_id"],
        message=message_text
    )

    print("Telegram sent successfully.")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Latest date: 2026-06-22 00:00:00
Start date: 2025-06-22 00:00:00
Rows after filter: 124023

,No,Material Name,Sold-to-party ID,Sold-to-party Name,Ship-to-party ID,Ship-to-party Name,Sales Order No,Delivery No,Billing Doc.,Reference,...,Trans/TO (ZR15),Disc. on Trans (ZR20),COGS,COGS (per),COGS (per UOM),Special Discount,Disc COD (ZR22),Disc on Transport (ZR23),Search Term,Insert_Date
170502,NaN,PVC ECO Pipe 8.5 bar 80mm x 4m - Blue,12001943,LIM SIEK,15016128,Boeng Thom,67855225.0,800175715,21468881.0,21468881.0,...,0.0,0.0,5.56,1,PC,0.0,0.0,0.00,010882287,NaN
170698,NaN,Fitting Tee 8.5 Bar 80mm - Blue,12001943,LIM SIEK,12001943,LIM SIEK,67855277.0,800175775,21468918.0,21468918.0,...,0.0,0.0,0.69,1,PC,0.0,0.0,-1.05,010882287,NaN
170699,NaN,PVC Fitting Tee 8.5 Bar 100mm - Blue,12001943,LIM SIEK,12001943,LIM SIEK,67855277.0,800175775,21468918.0,21468918.0,...,0.0,0.0,1.08,1,PC,0.0,0.0,-2.54,010882287,NaN
170700,NaN,TY 80mm 8.5 Bar - Blue,12001943,LIM SIEK,12001943,LIM SIEK,67855277.0,800175775,21468918.0,21468918.0,...,0.0,0.0,0.83,1,PC,0.0,0.0,-1.91,010882287,NaN
170701,NaN,Conduit 20mm - White,12001943,LIM SIEK,12001943,LIM SIEK,67855277.0,800175775,21468918.0,21468918.0,...,0.0,0.0,0.47,1,PC,0.0,0.0,-6.00,010882287,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299474,NaN,Tee 55mm 8.5 bar - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67888683.0,800315526,21707595.0,21707595.0,...,0.0,0.0,0.26,1,PC,0.0,0.0,-0.19,010882287,NaN
299475,NaN,Socket 80mm x 55mm 8.5 Bar - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67888683.0,800315526,21707595.0,21707595.0,...,0.0,0.0,0.21,1,PC,0.0,0.0,-0.30,010882287,NaN
299476,NaN,Fitting Tee 8.5 Bar 80mm - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67888683.0,800315526,21707595.0,21707595.0,...,0.0,0.0,0.44,1,PC,0.0,0.0,-0.49,010882287,NaN
299477,NaN,PVC Fitting Tee 8.5 Bar 100mm - Blue,12001943,LIM SIEK,15000504,Wat Pothinheanh,67888683.0,800315526,21707595.0,21707595.0,...,0.0,0.0,0.76,1,PC,0.0,0.0,-0.08,010882287,NaN
299478,NaN,Chip Mong Pipe 8.5 Bar 40mm x 4m - Blue,12001943,LIM SIEK,12001943,LIM SIEK,67888686.0,800315530,21707597.0,21707597.0,...,0.0,0.0,2.01,1,PC,0.0,0.0,-23.50,010882287,NaN

Telegram sent successfully.